// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAk6d00xJDQ99CE43cYY7GnXrMiFxvMwM',
    appId: '1:1056621198278:web:3973ef1fe217a2e7e110c7',
    messagingSenderId: '1056621198278',
    projectId: 'rsb-corp',
    authDomain: 'rsb-corp.firebaseapp.com',
    storageBucket: 'rsb-corp.firebasestorage.app',
    measurementId: 'G-MJP604XZW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZFuvYUAl5btTQmjmggwaGRj9oi_3nKTE',
    appId: '1:1056621198278:android:58de552113580075e110c7',
    messagingSenderId: '1056621198278',
    projectId: 'rsb-corp',
    storageBucket: 'rsb-corp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7zFwQRMN3IogUt9ZbWJvykpbO5bJ3PEU',
    appId: '1:1056621198278:ios:5dc81f4988995c32e110c7',
    messagingSenderId: '1056621198278',
    projectId: 'rsb-corp',
    storageBucket: 'rsb-corp.firebasestorage.app',
    iosBundleId: 'com.example.rsbwebV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7zFwQRMN3IogUt9ZbWJvykpbO5bJ3PEU',
    appId: '1:1056621198278:ios:5dc81f4988995c32e110c7',
    messagingSenderId: '1056621198278',
    projectId: 'rsb-corp',
    storageBucket: 'rsb-corp.firebasestorage.app',
    iosBundleId: 'com.example.rsbwebV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAk6d00xJDQ99CE43cYY7GnXrMiFxvMwM',
    appId: '1:1056621198278:web:da1fb9e57d267bfee110c7',
    messagingSenderId: '1056621198278',
    projectId: 'rsb-corp',
    authDomain: 'rsb-corp.firebaseapp.com',
    storageBucket: 'rsb-corp.firebasestorage.app',
    measurementId: 'G-3RF2B110KG',
  );
}
